Allow collections to not have a version when collecting existing files.
bumpybox/pyblish-bumpybox pull request #17
Opened 2017-06-23 14:48 UTC by tokejepsen

Previously when scanning for existing files, an error would occur when there was no version number in the collections file name.
This will allow collections to not be forced to have version numbers in the file name.

This was spawned by working on the NukeStudio workflow where collections of transcoded images doesn't not have a version number in the file name.

2017-06-27 14:59 UTC, iwootten requested changes

2017-06-27 14:59 UTC, iwootten commented on pyblish_bumpybox/plugins/collect_existing_files.py
> +    def scan_collection(self, collection):
From what I see, this method should be static.

2017-06-27 14:59 UTC, iwootten commented on pyblish_bumpybox/plugins/collect_existing_files.py
> +        if scan_dir not in self.scanned_dirs and os.path.exists(scan_dir):
scanned_dirs and files shouldn't be class members, given they aren't used anywhere but this function.

2017-06-27 14:59 UTC, iwootten commented on pyblish_bumpybox/plugins/collect_existing_files.py
> +            self.scanned_dirs.append(scan_dir)
You could simplify this by only sending a unique collection and not having to maintain a list.

2017-06-27 14:59 UTC, iwootten commented on pyblish_bumpybox/plugins/collect_existing_files.py
> +    def scan_versions(self, instance_collection, version):
This should be a static method, given the call to scan_collection can also be static.

2017-06-28 07:36 UTC, tokejepsen commented on pyblish_bumpybox/plugins/collect_existing_files.py
> +            self.scanned_dirs.append(scan_dir)
The idea of maintaining a list of scanned directories and files, was to optimize scanning the files on disk to only collect once.
The case would be when a collection does not have a unique parent directory. The only asset type which has a unique parent directory is ```img```.
This should illustrate the situation:

- workspace
    - image sequence parent directory
        - image.####.exr
    - one_cache.####.abc
    - two_caches.####.abc

2017-06-28 08:54 UTC, iwootten commented on pyblish_bumpybox/plugins/collect_existing_files.py
> +            self.scanned_dirs.append(scan_dir)
Ok, I still think these shouldn't be class-level vars though. Additionally, you could separate the scanning from the matching into two different methods to make things easier to test.

2017-06-28 09:06 UTC, tokejepsen commented on pyblish_bumpybox/plugins/collect_existing_files.py
> +            self.scanned_dirs.append(scan_dir)
Could you elaborate on why its easier to test?
I don't know a lot about testing so would like to know the reason.

2017-06-28 10:26 UTC, iwootten commented on pyblish_bumpybox/plugins/collect_existing_files.py
> +            self.scanned_dirs.append(scan_dir)
Sure, writing smaller functions that do less is generally encouraged given it offers greater flexibility on how those functions might be used and cleaner simpler code.

Generally you write functions that perform a single thing - which is simpler to test. With smaller functions, you can write tests for each smaller function with simpler logic. What this function is doing is really a scan_and_match, so any test you might write has to test both behaviours. That can lead to confusing tests that are trying to test more complex logic. 

Much of this is hypothetical given there are currently no unit tests for this repo.

2017-06-28 10:28 UTC, iwootten commented on pyblish_bumpybox/plugins/collect_existing_files.py
> +            self.scanned_dirs.append(scan_dir)
Here's a good thread on some of the above: https://stackoverflow.com/questions/475675/when-is-a-function-too-long

2017-06-28 13:04 UTC, tokejepsen commented
Last commit was a fairly big rewrite, but I think the code is more logical now
Let me know what you think.

2017-06-28 14:45 UTC, iwootten commented on pyblish_bumpybox/plugins/collect_existing_files.py
> +            version_collection.name = collection.name
Can these collection variable assignments be done as part of the version_collection creation above?

2017-06-28 14:45 UTC, iwootten commented on pyblish_bumpybox/plugins/collect_existing_files.py
> +    def match_files_collection(self, files, collection):
I guess a more descriptive method name here might be something like get_files_in_collection?

2017-06-28 15:23 UTC, tokejepsen commented on pyblish_bumpybox/plugins/collect_existing_files.py
> +            version_collection.name = collection.name
No, the ```clique.Collection``` method does not work like that.

Assigning the variables to the collection object is a work around for how the code is structured.

2017-06-28 15:24 UTC, tokejepsen commented on pyblish_bumpybox/plugins/collect_existing_files.py
> +    def match_files_collection(self, files, collection):
Maybe, although you aren't getting the files in the collection, you are matching external files to the collection.

2017-06-28 15:28 UTC, iwootten commented on pyblish_bumpybox/plugins/collect_existing_files.py
> +    def match_files_collection(self, files, collection):
So perhaps populate_collection?

2017-06-28 15:30 UTC, iwootten commented on pyblish_bumpybox/plugins/collect_existing_files.py
> +    def match_files_collection(self, files, collection):
Another minor thing, I'd probably expect for the collection to be the first argument in this call too.

2017-06-28 15:32 UTC, tokejepsen commented on pyblish_bumpybox/plugins/collect_existing_files.py
> +    def match_files_collection(self, files, collection):
Works for me :) Done.

2017-06-28 16:45 UTC, iwootten approved these changes

2017-06-28 16:45 UTC, merged