Single file Ftrack components
bumpybox/pyblish-bumpybox pull request #18
Opened 2017-06-26 15:22 UTC by tokejepsen

This allows for having single file outputs with the datamember instance.data["output"].

2017-06-27 15:02 UTC, iwootten requested changes

2017-06-27 15:02 UTC, iwootten commented on pyblish_bumpybox/plugins/nuke/collect_nuke_groups.py
> +                instance.data["output"] = os.path.join(
It's unclear from the variable name here what it represents.

2017-06-27 15:06 UTC, tokejepsen commented on pyblish_bumpybox/plugins/nuke/collect_nuke_groups.py
> +                instance.data["output"] = os.path.join(
Have you got a suggestion for something better?

2017-06-27 15:39 UTC, iwootten commented on pyblish_bumpybox/plugins/nuke/collect_nuke_groups.py
> +                instance.data["output"] = os.path.join(
To me, the original name was more indicative of what it represented. Output could be any variable type - path would suggest a string. I'd lose the camelcasing though if anything.

2017-06-27 15:46 UTC, tokejepsen commented on pyblish_bumpybox/plugins/nuke/collect_nuke_groups.py
> +                instance.data["output"] = os.path.join(
Cool, I can go back to the original variable name.

```mixedCase``` has been suggested by Marcus for any data members, which I have been stuck to.

2017-06-27 15:57 UTC, iwootten commented on pyblish_bumpybox/plugins/nuke/collect_nuke_groups.py
> +                instance.data["output"] = os.path.join(
Really? Why is that? That's counter to PEP8 recommendations?

2017-06-27 16:12 UTC, iwootten commented on pyblish_bumpybox/plugins/nuke/collect_nuke_groups.py
> +                instance.data["output"] = os.path.join(
In fact, elsewhere in this PR you use drop cased key names, I think we should stick to a single convention and in my mind it should be the same as the naming used for variables.

2017-06-28 07:23 UTC, tokejepsen commented
What do you think now?

2017-06-28 07:27 UTC, iwootten commented
Hey, this looks fine to me.

2017-06-28 07:27 UTC, iwootten approved these changes

2017-06-28 07:27 UTC, merged